### ISSUE TITLE
Application run failed

### ISSUE THREAD

**Issue by 53845714nF** [dailycodework/dream-shops#1]
Hi, I want to use your project a Base for some [Experiments](https://github.com/53845714nF/ContainerBench4Spring) with Spring on Docker.
I try to pack your Applications in Container, but the run failed with the following Command:

```text
dreamshop-1  | 2024-09-06T17:01:19.227Z  INFO 1 --- [dream-shops] [           main] c.d.dreamshops.DreamShopsApplication     : Started DreamShopsApplication in 45.902 seconds (process running for 50.117)
dreamshop-1  | Hibernate: 
dreamshop-1  |     select
dreamshop-1  |         r1_0.id,
dreamshop-1  |         r1_0.name 
dreamshop-1  |     from
dreamshop-1  |         role r1_0 
dreamshop-1  |     where
dreamshop-1  |         r1_0.name=?
dreamshop-1  | 2024-09-06T17:01:20.227Z ERROR 1 --- [dream-shops] [           main] o.s.boot.SpringApplication               : Application run failed
```

What could I do?

**Comment by dailycodework** [comment]
Maybe you can do some research on that by checking out some videos and blogs for docker images and containers

**Comment by 53845714nF** [comment]
Thank you,
I'm looking for another project for my experiments. You are too incompetent for me.
